# Generated by Django 4.0.7 on 2022-10-12 00:06

from django.db import migrations, models
import django_extensions.db.fields
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ubicacion', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='nombre_ubicacion')),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['nombre_ubicacion'],
            },
        ),
        migrations.AddField(
            model_name='agregarpropiedad',
            name='barrio',
            field=models.CharField(blank=True, help_text='Barrio', max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='agregarpropiedad',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='agregarpropiedad',
            name='ubicacion',
            field=modelcluster.fields.ParentalManyToManyField(to='house.ubicaciones'),
        ),
    ]
